apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kuiper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuiper.labels" . | nindent 4 }}
data:
    "random.yaml": |
      default:
        interval: 1000
        pattern:
          count: 50
      ext:
        interval: 300
        seed: 1
        pattern:
          count: 50
    "zmq.yaml": |
      #Global Zmq configurations
      default:
        server: tcp://127.0.0.1:5563
    "mqtt.yaml": |
      #Global MQTT configurations
      default:
        {{- toYaml .Values.mqtt | nindent 8 }}
      #Override the global configurations
      demo_conf: #Conf_key
        qos: 0
        servers: [tcp://10.211.55.6:1883, tcp://127.0.0.1]
    "client.yaml": |
      basic:
        host: 127.0.0.1
        port: 20498
    "kuiper.yaml": |
      basic:
        # true|false, with debug level, it prints more debug info
        debug: false
        port: 20498