apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuiper.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuiper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  selector:
    {{- include "kuiper.selectorLabels" . | nindent 4 }}