apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kuiper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuiper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "kuiper.fullname" . }}-headless
  {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: kuiper-data
        namespace: {{ .Release.Namespace }}
        labels:
          {{- include "kuiper.labels" . | nindent 4 }}
        annotations:
        {{- if .Values.persistence.storageClass }}
          volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
        {{- else }}
          volume.alpha.kubernetes.io/storage-class: default
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
         requests:
           storage: {{ .Values.persistence.size | quote }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kuiper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kuiper.selectorLabels" . | nindent 8 }}
    spec:
      # securityContext:
      #   fsGroup: 1000
      volumes:
      {{- if not .Values.persistence.enabled }}
      - name: kuiper-data
        emptyDir: {}
      {{- else if .Values.persistence.existingClaim }}
      - name: kuiper-data
        persistentVolumeClaim:
        {{- with .Values.persistence.existingClaim }}
          claimName: {{ tpl . $ }}
        {{- end }}
      {{- end }}
      - name: mqtt
        configMap:
          name: {{ include "kuiper.fullname" . }}
          items:
          - key: mqtt.yaml
            path: mqtt.yaml
      containers:
        - name: kuiper
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: kuiper-data
            mountPath: "/kuiper/data"
          - name: mqtt
            mountPath: "/kuiper/etc/sources/mqtt.yaml"
            subPath: "mqtt.yaml"
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

          # readinessProbe:
          #   httpGet:
          #     path: /status
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 5